// <auto-generated />
using System;
using AnimeWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimeWeb.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231023155147_CreacionDeLaTablaVideo")]
    partial class CreacionDeLaTablaVideo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("AnimeWeb.Models.AnimeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("state")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("updateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("uploadDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Anime");
                });

            modelBuilder.Entity("AnimeWeb.Models.ChapterModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("animeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("episode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("state")
                        .HasColumnType("INTEGER");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("updateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("uploadDate")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("animeId");

                    b.ToTable("Capitulo");
                });

            modelBuilder.Entity("AnimeWeb.Models.VideoModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("idChapter")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("state")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("updateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("uploadDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("idChapter");

                    b.ToTable("Video");
                });

            modelBuilder.Entity("AnimeWeb.Models.ChapterModel", b =>
                {
                    b.HasOne("AnimeWeb.Models.AnimeModel", "AnimeModel")
                        .WithMany("chapters")
                        .HasForeignKey("animeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnimeModel");
                });

            modelBuilder.Entity("AnimeWeb.Models.VideoModel", b =>
                {
                    b.HasOne("AnimeWeb.Models.ChapterModel", "ChapterModel")
                        .WithMany("videos")
                        .HasForeignKey("idChapter")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChapterModel");
                });

            modelBuilder.Entity("AnimeWeb.Models.AnimeModel", b =>
                {
                    b.Navigation("chapters");
                });

            modelBuilder.Entity("AnimeWeb.Models.ChapterModel", b =>
                {
                    b.Navigation("videos");
                });
#pragma warning restore 612, 618
        }
    }
}
